//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weighing.Terminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OracleHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OracleHeader()
        {
            this.TaskTimbangs = new HashSet<TaskTimbang>();
        }

        public long OracleHeaderId { get; set; }
        public long MOHeaderId { get; set; }
        public long MOLineId { get; set; }
        public string MoNumber { get; set; }
        public long LineNumber { get; set; }
        public string FromSubInventoryCode { get; set; }
        public string ToSubInventoryCode { get; set; }
        public System.DateTime DateRequired { get; set; }
        public string SourceType { get; set; }
        public string DocNumber { get; set; }
        public string Customer { get; set; }
        public string ShipTo { get; set; }
        public string Requestor { get; set; }
        public string ItemCode { get; set; }
        public string ItemDesc { get; set; }
        public string ItemDescAlias { get; set; }
        public string UOM { get; set; }
        public decimal Qty { get; set; }
        public Nullable<int> UrutanTuang { get; set; }
        public Nullable<decimal> QtyPerCharge { get; set; }
        public string Activity { get; set; }
        public string CombineL1 { get; set; }
        public string CombineL2 { get; set; }
        public Nullable<decimal> PackingSize { get; set; }
        public int SelfLife { get; set; }
        public bool IsTimbang { get; set; }
        public bool IsClosedCode { get; set; }
        public bool IsAllergen { get; set; }
        public bool IsProcessed { get; set; }
        public string UsrCrt { get; set; }
        public System.DateTime DtmCrt { get; set; }
        public string UsrUpd { get; set; }
        public System.DateTime DtmUpd { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskTimbang> TaskTimbangs { get; set; }
    }
}
