//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weighing.Preparation.Models
{
    using OanTech.Common;
    using System;
    using System.Collections.Generic;

    public partial class OracleDetail : ITimeStamp
    {
        public long OracleDetailId { get; set; }
        public long OracleHeaderId { get; set; }
        public long MOHeaderId { get; set; }
        public long MOLineId { get; set; }
        public string MONumber { get; set; }
        public string ItemCode { get; set; }
        public string LotNo { get; set; }
        public decimal LotQty { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public bool IsProcessed { get; set; }
        public string UsrCrt { get; set; }
        public System.DateTime DtmCrt { get; set; }
        public string UsrUpd { get; set; }
        public System.DateTime DtmUpd { get; set; }

        public virtual OracleHeader OracleHeader { get; set; }
    }
}
