//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weighing.Oracle.Models
{
    using System;
    using System.Collections.Generic;

    public partial class XSHP_TIMBANG_ALOKASI
    {
        public long ID { get; set; }
        public long MO_HEADER_ID { get; set; }
        public long MO_LINE_ID { get; set; }
        public long TRANSACTION_TEMP_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string LOT_NO { get; set; }
        public decimal LOT_QTY { get; set; }
        public System.DateTime EXPIRATION_DATE { get; set; }
        public bool IS_PROCESSED { get; set; }
    }
}
