//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weighing.Oracle.Models
{
    using System;
    using System.Collections.Generic;

    public partial class XSHP_TIMBANG
    {
        public long ID { get; set; }
        public long MO_HEADER_ID { get; set; }
        public long MO_LINE_ID { get; set; }
        public string MO_NUMBER { get; set; }
        public string MO_TYPE { get; set; }
        public long LINE_NUMBER { get; set; }
        public string FROM_SUBINVENTORY_CODE { get; set; }
        public string TO_SUBINVENTORY_CODE { get; set; }
        public System.DateTime DATE_REQUIRED { get; set; }
        public string SOURCE_TYPE { get; set; }
        public string DOC_NUMBER { get; set; }
        public string CUSTOMER { get; set; }
        public string SHIP_TO { get; set; }
        public string REQUESTOR { get; set; }
        public string ITEM_CODE { get; set; }
        public string ITEM_DESC { get; set; }
        public string ITEM_DESC_ALIAS { get; set; }
        public string UOM { get; set; }
        public decimal QTY { get; set; }
        public Nullable<int> URUTAN_TUANG { get; set; }
        public Nullable<decimal> QTY_PER_CHARGE { get; set; }
        public string ACTIVITY { get; set; }
        public string COMBINE_LV1 { get; set; }
        public string COMBINE_LV2 { get; set; }
        public Nullable<decimal> PACKING_SIZE { get; set; }
        public int SELF_LIFE { get; set; }
        public bool IS_TIMBANG { get; set; }
        public bool IS_CLOSED_CODE { get; set; }
        public bool IS_ALLERGEN { get; set; }
        public bool IS_PROCESSED { get; set; }
    }
}
